### ISSUE TITLE
get PKCS10 (Step 4)

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-pki-integration#108]
- [ ]  how do we store the certificate needs to be clarified
- [ ] do we need the plattform to store the certificate

**Comment by kreinhar** [comment]
#34

**Comment by iviliev** [comment]
The endpoint for retrieving/storing certificates is :  /tenant/tenants/<tenantId>/trusted-certificates (https://cumulocity.com/guides/10.7.0/reference/tenants/)

**Comment by kreinhar** [comment]
we are not doing pkcs 10 at the moment
it generated on the agent side
